### ISSUE TITLE
NameError: name 'reduce' is not defined 

### ISSUE THREAD

**Issue by wajihullahbaig** [luannd/MinutiaeNet#6]
```
MinutiaeNet-master/CoarseNet/CoarseNet_utils.py in merge_sum(x)
    193     return reduce(lambda x,y:x*y, x)
    194 def merge_sum(x):
--> 195     return reduce(lambda x,y:x+y, x)
    196 
    197 

NameError: name 'reduce' is not defined
```

Could not find the function mentioned above

**Comment by luannd** [comment]
This is another question with python 3. You can read this [link](https://stackoverflow.com/questions/8689184/nameerror-name-reduce-is-not-defined-in-python) for more details.
The problem can be fixed by `from functools import reduce` in python 3. If it solves, let me know and I will close this issue.

**Comment by wajihullahbaig** [comment]
Thank you for the reply. 
Yes it was a Python3 error. I have forked your code and I am making it Python3 compatible. You can find it here. 
https://github.com/wajihullahbaig/MinutiaeNet

You can close this issue.
